package hw;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DAO {
	public Connection myGetConnection() {
		
		/*Connection class helps to establish a connection with the database*/
		
		Connection connect=null;
		try {
		//Load the class from jar to RAM
		Class.forName("com.mysql.cj.jdbc.Driver");
		//url-->Protocol:dbvendor://IP:portname/database
		
		String url="jdbc:mysql://localhost:3306/ietmar2022";
		String uname="root";
		String pwd="2022";
				
		connect = DriverManager.getConnection(url,uname,pwd);
		}
		catch(ClassNotFoundException|SQLException e) {
			System.out.println("the connection could not be made"+e);
		}
		return connect;
	}
	
	/*ResultSet object is a table of data representing a database result set,
	  which is usually generated by executing a statement that queries the database.*/

	/*this is by normal statement*/	
	
//	public ResultSet getRows(String sql) {
//		Connection con=myGetConnection();
//		ResultSet rs=null;
//		Statement stmt=null;
//		try {
//			stmt=con.createStatement();
//			rs=stmt.executeQuery(sql);
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		return rs;
//	}
	
/*this is by using PrepareStatement*/	
	
	public ResultSet getRows(String sql) {
		Connection con=myGetConnection();
		ResultSet rs=null;
		PreparedStatement pstmt=null;
		try {
			pstmt=con.prepareStatement(sql);
			rs=pstmt.executeQuery(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return rs;
	}
	
	//displaying resultset
	public void showResultSet(ResultSet rs) {
		try {
			
			while(rs.next()) {
			int pID=rs.getInt("id");
			String pName=rs.getString("name");
			int cost=rs.getInt(3);//column index
			
			System.out.println(pID+" "+pName+" "+ cost);
		}
		}
		catch(SQLException e) {
			System.out.println("Problem showing result "+ e);	
		}
		}

	public void addProducts(int id,String name,int cost) {
		Connection con=myGetConnection();
		try{
			PreparedStatement pstmt=con.prepareStatement("insert into product values(?,?,?)");
			pstmt.setInt(1, id);
			pstmt.setString(2, name);
			pstmt.setInt(3, cost);
			pstmt.executeUpdate();
		}
		catch(SQLException e) {
			System.out.println("Problem: "+e);
		}
	}
	
	public void addProducts(String name,int cost) {
		Connection con=myGetConnection();
		try{
			//tied up with sql that means only inserted query we can execute
			PreparedStatement pstmt=con.prepareStatement("insert into product values(default,?,?)");
			pstmt.setString(1, name);
			pstmt.setInt(2, cost);
			pstmt.executeUpdate();
		}
		catch(SQLException e) {
			System.out.println("Problem: "+e);
		}
	}
	
	public void updateCost(int id,int cost) {
		Connection con=myGetConnection();
		try {
			PreparedStatement pstmt=con.prepareStatement("Update product set cost=? where id=?");
			pstmt.setInt(1, cost);
			pstmt.setInt(2, id);
			pstmt.executeUpdate();
		}
		catch(SQLException e) {
			System.out.println("Problem: "+e);
		}
	}
	
	public void deleteRecord(int id)
	{
		Connection con = myGetConnection();
		try {
			PreparedStatement psmt = con.prepareStatement("delete from product where id =?");
		
			
			psmt.setInt(1, id);
			
			psmt.executeUpdate();
		
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
	}
	
	
}



